package ru.liga.commons.status;

public enum StatusOrders {
    CUSTOMER_CREATED,
    CUSTOMER_PAID,
    CUSTOMER_CANCELLED,
    KITCHEN_ACCEPTED,
    KITCHEN_PREPARING,
    KITCHEN_DENIED,
    KITCHEN_REFUNDED,
    DELIVERY_PENDING,
    DELIVERY_PICKING,
    DELIVERY_DENIED,
    DELIVERY_REFUNDED,
    DELIVERY_DELIVERING,
    DELIVERY_COMPLETE
}
